### ISSUE TITLE
Relicensing proposal

### ISSUE THREAD

**Issue by mdziekon** [radarsu/validate-polish#6]
Hi @radarsu, I've noticed that this library does not explicitly state what license does it use, however according to `package.json` it is supposed to be GPL-3.0 licensed. This license makes this library essentially useless for any larger project (commercial or not, except for GPL-licensed project obviously), because GPL is considered to be a viral license, forcing the code which uses it (in most cases) to also be licensed using GPL.

Would you consider relicensing your library to a more permissive license, eg. MIT, Apache or BSD-3-clause? Conversely, if this was not your intention to license it as GPL-3.0 (IANAL, but currently your code does not include the required copy of the GPL license), could you please include the desired license text and also update the package.json accordingly?

**Comment by radarsu** [comment]
Sure, I will change the license to MIT.

EDIT: Actually, validate-polish version on the npm is already under MIT, I just didn't update github repository, will do that soon.
https://www.npmjs.com/package/validate-polish
